# Generated by Django 2.0.5 on 2018-05-20 06:13

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180520_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Зоголовок')),
                ('image', models.ImageField(upload_to=main.utils.ad_image_path, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсоры',
            },
        ),
    ]
