# Generated by Django 2.0.5 on 2018-06-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Зоголовок'),
        ),
    ]
