# Generated by Django 2.0.5 on 2018-08-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180605_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollanswer',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, verbose_name='Ip адресс'),
        ),
    ]
